steps:                                                                                                                                                         
  - name: gcr.io/cloud-builders/gcloud
    args:
      - source
      - repos
      - clone
      - default
      - /workspace/default
  - name: bash
    args:
      - cp
      - /workspace/default/tr-project-rest/settings.py
      - ./settings.py
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${PROJECT_ID}/tr-projects-rest:${BRANCH_NAME}_${SHORT_SHA}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/tr-projects-rest
images:
  - gcr.io/$PROJECT_ID/tr-projects-rest
